services:
  - type: web
    name: trading-toolkit-api
    runtime: docker
    dockerfilePath: ./cloudrun/Dockerfile
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 8080
    healthCheckPath: /api/v1/admin/health
