"""baseline schema

Revision ID: 9c3cae4c1a70
Revises:
Create Date: 2026-07-24 18:20:04.030117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c3cae4c1a70'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convertible_timeline',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('bond_code', sa.String(length=20), nullable=True),
    sa.Column('stage_dates', sa.Text(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code', name='uq_convertible_timeline_stock')
    )
    op.create_index(op.f('ix_convertible_timeline_stock_code'), 'convertible_timeline', ['stock_code'], unique=False)
    op.create_table('placement_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('stock_name', sa.String(length=50), nullable=False),
    sa.Column('bond_code', sa.String(length=20), nullable=True),
    sa.Column('bond_name', sa.String(length=50), nullable=True),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('issue_size', sa.Float(), nullable=True),
    sa.Column('shareholder_amount', sa.Float(), nullable=True),
    sa.Column('shareholder_ratio', sa.Float(), nullable=True),
    sa.Column('online_amount', sa.Float(), nullable=True),
    sa.Column('online_ratio', sa.Float(), nullable=True),
    sa.Column('underwriter_amount', sa.Float(), nullable=True),
    sa.Column('announce_date', sa.String(length=20), nullable=True),
    sa.Column('announcement_id', sa.String(length=30), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('announcement_id', name='uq_placement_announcement')
    )
    op.create_index(op.f('ix_placement_result_stock_code'), 'placement_result', ['stock_code'], unique=False)
    op.create_table('user_favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('premium_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openid', 'code', 'type', name='uq_user_fav')
    )
    op.create_index(op.f('ix_user_favorites_openid'), 'user_favorites', ['openid'], unique=False)
    op.create_table('user_reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('remind_type', sa.String(length=20), nullable=False),
    sa.Column('remind_value', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openid', 'code', 'type', 'remind_type', name='uq_user_reminder')
    )
    op.create_index(op.f('ix_user_reminders_openid'), 'user_reminders', ['openid'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=False),
    sa.Column('theme', sa.String(length=10), nullable=True),
    sa.Column('default_tab', sa.String(length=20), nullable=True),
    sa.Column('remind_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_reminders_openid'), table_name='user_reminders')
    op.drop_table('user_reminders')
    op.drop_index(op.f('ix_user_favorites_openid'), table_name='user_favorites')
    op.drop_table('user_favorites')
    op.drop_index(op.f('ix_placement_result_stock_code'), table_name='placement_result')
    op.drop_table('placement_result')
    op.drop_index(op.f('ix_convertible_timeline_stock_code'), table_name='convertible_timeline')
    op.drop_table('convertible_timeline')
    # ### end Alembic commands ###
